- .husky/pre-commit
- package.json
- yarn.lock
Upgrade Husky to version 7 and add typescript file extensions to `lint-staged` script
> Fix: husky

- .eslintrc.json
- src/Button/index.tsx
- src/Button/style.css
Fix Formatting indents rules for code and Styling for the Buttons Components
> Fix Indent Rules & Button Styling

- package.json
- src/Tag/index.tsx
- src/Tag/stories/index.stories.tsx
- src/Tag/style.css
- tsconfig.json
> add tag component

- src/Avatar/index.tsx
- src/Avatar/stories/index.stories.tsx
- src/Avatar/style.css
- src/AvatarGroup/index.tsx
- src/AvatarGroup/stories/index.stories.tsx
- src/AvatarGroup/style.css
- src/index.tsx
components Avatar and AvatarGroup
> [Develop] components Avatar, AvatarGroup

- src/Button/stories/defaultButton.stories.tsx
- src/Button/stories/iconButton.stories.tsx
- src/Button/stories/smallButton.stories.tsx
- src/Button/style.css
> Update Button large styling, add sm,md styling

- src/Button/index.tsx
fixed an issue where `className` is not passed as prop to the `Button` component
> [Develop] Button component: pass correct value as prop

- src/Input/stories/index.stories.tsx
- src/Input/stories/search.stories.tsx
- src/Input/style.css
- src/Select/index.tsx
- src/Select/stories/index.stories.tsx
- src/Select/style.css
- src/assets/style/form-item.css
- src/index.tsx
> Fix search-input icon styling

- src/Input/style.css
> Remove dependent on the form css on input css

- .github/workflows/storybook.yml
- package.json
> storybook: github pages host action

- src/index.tsx
included missing components, props imports
> [Develop] Missing components index

- src/Breadcrumb/index.tsx
- src/Breadcrumb/stories/index.stories.tsx
- src/Breadcrumb/style.css
- src/index.tsx
> Breadcrumb Component

- src/AutoComplete/stories/index.stories.tsx
- src/DatePicker/stories/index.stories.tsx
- src/DatePicker/stories/quarterPicker.stories.tsx
- src/DatePicker/stories/rangePicker.stories.tsx
- src/Input/stories/index.stories.tsx
- src/Input/stories/search.stories.tsx
- src/Input/style.css
- src/Select/stories/index.stories.tsx
- src/Select/style.css
> Fix/form label styling, input and select styling

- src/Menu/style.css
- src/Table/style.css
refactored menu css code because there were issues affecting `Dropdown` and `Layout` components
> [Develop] refactored menu css

- src/Select/style.css
> Fixed focus/unfocus caret animation

- src/PageHeader/style.css
> Change Back Icon Color

- src/DatePicker/index.tsx
- src/DatePicker/stories/index.stories.tsx
- src/DatePicker/stories/quarterPicker.stories.tsx
- src/DatePicker/stories/rangePicker.stories.tsx
- src/DatePicker/style.css
- src/TimePicker/stories/index.stories.tsx
- src/TimePicker/stories/rangePicker.stories.tsx
- src/TimePicker/style.css
- src/index.tsx
> [Develop] Fave 17574 Time Picker

- src/List/index.tsx
- src/index.tsx
added ListItemMeta subcomponent for List component
> [Develop] added ListItemMeta subcomponent for List component

- src/Mentions/index.tsx
- src/Mentions/stories/index.stories.tsx
- src/Mentions/style.css
- src/index.tsx
> [Develop] Fave 17954 mentions

- src/Input/index.tsx
- src/Input/style.css
- src/index.tsx
added input textarea to be used with Comment component
> [Develop] added input textarea

- src/index.tsx
include back missing tree select component which was removed in this PR;
- https://github.com/kfit-dev/ui-components/pull/94
> [Develop] Add missing tree select component

- .eslintrc.json
- src/Comment/index.tsx
- src/Comment/stories/index.stories.tsx
- src/Comment/style.css
- src/index.tsx
> [Develop] created new Comment component

- .eslintrc.json
- package-lock.json
- package.json
- src/Breadcrumb/style.css
- src/Card/index.tsx
- src/Card/stories/index.stories.tsx
- src/Comment/index.tsx
- src/Comment/stories/index.stories.tsx
- src/Comment/style.css
- src/Dropdown/stories/index.stories.tsx
- src/Input/index.tsx
- src/Input/style.css
- src/Layout/stories/index.stories.tsx
- src/Menu/index.tsx
- src/Menu/stories/index.stories.tsx
- src/Popover/style.css
- src/Radio/stories/index.stories.tsx
- src/Tree/index.tsx
- src/Tree/stories/index.stories.tsx
- src/index.tsx
- yarn.lock
> Upgrade/ant design version 4.20.0

- package.json
> [Develop] new version 0.1.21

- src/Modal/index.tsx
> Fix modal - cancel button unable to add props

- src/Button/style.css
> Fix icon buttons component min height styling issues

- src/Dropdown/style.css
> Fix dropdown menu padding styling issue

- src/Popover/style.css
> Fix popover content styling issue

- src/PageHeader/style.css
> Fix page header padding styling

- src/Form/index.tsx
- src/Form/stories/index.stories.tsx
- src/Form/style.css
- src/index.tsx
> Add Form Component

- src/Layout/style.css
> Fix layout sider component  z-index issue

- src/Tooltip/style.css
> Fix Tooltip arrow color

- rollup.config.js
> Reoder the import of styling

- package.json
> Upgrade fave-ui version 0.1.22

- src/Descriptions/index.tsx
- src/index.tsx
export `TabPane`, fix `Descriptions` import path
> [Develop] export tabpane, fix descriptions import

- package.json
> [Develop] changed version to 0.1.24

- package.json
> [Develop] upgrade version to 0.1.25

- src/Select/style.css
- src/Tree/style.css
- Select
- added height to match `Input` component height
- added padding to select items
- make text vertically aligned
- Tree
- highlight items that matches searched text in filter dropdown
> [Develop] Select, Tree component fixes

- src/Menu/style.css
> [Develop] menu items appear disabled

- package.json
> [Develop] upgrade version to 0.1.27

- package.json
- src/Menu/style.css
- src/Modal/index.tsx
- src/Select/style.css
- src/Tag/style.css
- src/Tree/style.css
This PR contains the following PR;
- https://github.com/kfit-dev/ui-components/pull/142
- https://github.com/kfit-dev/ui-components/pull/143
- https://github.com/kfit-dev/ui-components/pull/141
- https://github.com/kfit-dev/ui-components/pull/145
- https://github.com/kfit-dev/ui-components/pull/144
> [Main] upgrade to 0.1.27

- src/Modal/index.tsx
- src/Modal/style.css
- exported modal component properly, fixed CSS issues for modal component not matching with functional modals
> [Develop] exported modal component properly

- src/Empty/index.tsx
- make empty component more customisable
- added prop for custom title and description
- if no props are provided, `emptyType` will be set to `custom-image` by default, and use ANTD's default value
> [Develop] make empty component more customisable

- package.json
- upgrade version to 0.1.28 to include changes from the following PRs;
- https://github.com/kfit-dev/ui-components/pull/148
- https://github.com/kfit-dev/ui-components/pull/147
> [Develop] upgrade version to 0.1.28

- package.json
- src/Empty/index.tsx
- src/Modal/index.tsx
- src/Modal/style.css
- upgrade version to 0.1.28 to include changes from the following PRs;
- https://github.com/kfit-dev/ui-components/pull/149
- https://github.com/kfit-dev/ui-components/pull/148
- https://github.com/kfit-dev/ui-components/pull/147
> [Master] upgrade to 0.1.28
